### ISSUE TITLE
Is The Multi-Dimensional Thief finishable in AGiliTy?

### ISSUE THREAD

**Issue by DavidKinder** [DavidKinder/Windows-AGiliTy#3]
See https://intfiction.org/t/the-multi-dimensional-thief-broken-in-agility/52039

**Comment by angstsmurf** [comment]
FWIIW, I did some testing with the latest release of Windows AGiliTy and can confirm that it has the problems observed in the bug report.

**Comment by DavidKinder** [comment]
Splitting out the problems in detail ...

Known problems in The Multi-Dimensional Thief:
* "PUT HOLE ON FLOOR" doesn't work.
* "GET OUT" doesn't work, "TAKE OUT" does.
* Menu mode doesn't seem to work properly.

Known problems in Shades of Gray:
* "SIGNAL COMPANIONS" doesn't work.

**Comment by angstsmurf** [comment]
Yes, that's pretty much it. Also, note that *The Multi-Dimensional Thief* has reasonably well commented source code in here: https://ifarchive.org/if-archive/games/source/agt/mdthf1-s.zip

**Comment by DavidKinder** [comment]
I've started writing a log file to play through MD-Thief. Problems as they come up:

1) "PUT HOLE ON NORTH WALL" doesn't work. Fixed by work on https://github.com/DavidKinder/Windows-AGiliTy/issues/6.

2) "ENTER HOLE" doesn't work. Neither does "JUMP THROUGH HOLE", but "STEP THROUGH HOLE" and just "HOLE" do work. Fixed by work on https://github.com/DavidKinder/Windows-AGiliTy/issues/7.

3) At the waterfall, after "SWIM", only "TAKE OUT" gets back out. In the original "GET OUT" works too. Fixed by work on https://github.com/DavidKinder/Windows-AGiliTy/issues/8.

4) At the waterfall, "FILL PAIL WITH WATER" asks a disambiguation question, "sea water or noisy waterfall?", so you have to enter "FAILL PAIL WITH WATERFALL". This is because AGiliTy uses very simple disambiguation logic unless the configuration option PURE_DISAMBIG is set to 0. Given that the original seems to have smarter disambiguation, this is addressed by https://github.com/DavidKinder/Windows-AGiliTy/issues/9.

5) In the gallery, "ENTER PAINTING" doesn't work, but "STEP INTO PAINTING" does. This is the same problem as 2), and is also fixed by https://github.com/DavidKinder/Windows-AGiliTy/issues/7.

6) Once you have the leaflet and the paper, you can order items, which asks for an account number. But entering the right account is not recognized. Fixed by work on https://github.com/DavidKinder/Windows-AGiliTy/issues/10.

**Comment by angstsmurf** [comment]
Excellent work! Let me know if there is anything I can do to help.

**Comment by DavidKinder** [comment]
> Excellent work! Let me know if there is anything I can do to help.

There will definitely be testing to be done at some point soon.

**Comment by DavidKinder** [comment]
@angstsmurf There is a now a test script that completes the Multi-Dimensional Thief (only 30 points out of 50) in Generic/tests/mdthief.log. Would you give the latest code a try on your system and see if the test script finishes the game for you (run it with the REPLAY or REPLAY FAST commands).

**Comment by angstsmurf** [comment]
I tried it, and it works. Yay! Excellent work.

**Comment by DavidKinder** [comment]
As The Multi Dimensional Thief is now finishable, I'm going to mark this issue as closed. Next I'd like to generate a test script for Shades of Gray. Once that is working it will probably be time for a new release of AGiliTy.

**Comment by angstsmurf** [comment]
I have a [script for  Shades of Gray ](https://github.com/angstsmurf/spatterlight/blob/master/UITests/Supporting%20Files/Shades%20of%20Gray%20command%20script.txt)that I use for regression-testing Spatterlight, by the way, but as it relies on a particular sequence of random numbers it is probably not useful to you.

**Comment by DavidKinder** [comment]
It might be useful, but I'm hoping that David Welbourn's solution at http://plover.net/~davidw/sol/s/shade92.html will be enough.

**Comment by angstsmurf** [comment]
I don't expect you to try to get a full score in Shades of Gray, but I suspect that this is actually impossible, and possibly deliberate, as some kind of metaphor.
